# Generated by Django 3.1.5 on 2021-06-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_ask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('date', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
    ]
