# Generated by Django 3.1.5 on 2021-06-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.BigIntegerField(blank=True)),
                ('askId', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'reply',
                'managed': False,
            },
        ),
    ]
